### ISSUE TITLE
Docker run 시 관련 트러블 관련 문의합니다

### ISSUE THREAD

**Issue by tjkpolisher** [dj-twenty-six/dj-twenty-six.github.io#12]
본인 깃허브 페이지 링크 구현해서 브랜치(1.1.0/tjkpolisher)에 푸쉬 및 풀 리퀘스트를 완료했고, 도커 환경에서 실행 테스트 준비 중입니다. 현재까지 진행된 상황은 아래와 같습니다.  
```
$ docker pull httpd
$ docker build -t my-apache2 .
$ sudo docker images
REPOSITORY       TAG       IMAGE ID       CREATED         SIZE
my-apache2       latest    dff2b7b91ced   8 seconds ago   173MB
httpd            2.4       75a48b16cd56   8 hours ago     168MB
httpd            latest    75a48b16cd56   8 hours ago     168MB
airflow_custom   latest    a713ebd817fc   2 weeks ago     2.84GB
wordpress        latest    8c0f37ccd87f   4 weeks ago     666MB
redis            latest    da63666bbe9a   4 weeks ago     138MB
postgres         13        8a0aecdbe3e9   4 weeks ago     407MB
apache/airflow   2.7.1     cc416abd9d31   6 weeks ago     1.51GB
mysql            5.7       92034fe9a41f   2 months ago    581MB

$ sudo docker run -dit --name my-webapp -p 8080:80 my-apache2
9b4ab09f2e040de68846eb8e156cb472e02e684ee4d92d40c8635c84e31dc8fa
docker: Error response from daemon: driver failed programming external connectivity on endpoint my-webapp (dca2b14acb199a254458dc3d27e959191e41561519b3dd40bd60fea7e0cdcf2c): Bind for 0.0.0.0:8080 failed: port is already allocated.
```  
포트 배정 관련하여 위와 같이 에러가 발생하는데 사용 가능한 타 포트 확보하려면 어떻게 해야 하는지 알고 계시는 분께서 답변 해주시면 감사하겠습니다.

**Comment by shims94** [comment]
포트가 사용중이라고하는데 혹시 다른곳에서 켜져있는게 있는지 확인하거나 
포트를 8081로 바꾸는게 어떨까요?

**Comment by pySatellite** [comment]
failed: port is already allocated.

작성 로그 중에 위와 같은 메시지가 있네요. 이미 사용하는 포트를 사용하여 포트가 충돌하는 경우입니다.

**Comment by pySatellite** [comment]
또한 테스트 방법은 README.md 에 가이드된 Dockerfile 을 사용하는 방식으로 부탁드립니다.

**Comment by aaingyunii** [comment]
cmd에서 
`$ netstat -ano | findstr 8080` 

8080 포트를 사용 중인 프로세스를 찾고

`$ taskkill /f /pid [프로세스ID]` 

로 죽여서 하면 될거에요

저도 그런 에러가 나서 참고 사진 올립니다,

![image](https://github.com/dj-twenty-six/dj-twenty-six.github.io/assets/31847834/01208753-b697-4f58-9984-e3eaa3cb3cb1)

**Comment by tjkpolisher** [comment]
답변해주신 분들 모두 감사합니다. 현재 저는 기존 컨테이너 삭제 후 포트를 8081로 바꿔서 다시 실행하는 방법으로 해결했습니다.
![image](https://github.com/dj-twenty-six/dj-twenty-six.github.io/assets/80250150/334abe89-c5c2-497b-ab35-68a0b7ffa253)
