### ISSUE TITLE
버전관련건 1.1.0에서 요구사항을 반영해서 수정했을 때 버전업 관련 문의

### ISSUE THREAD

**Issue by shims94** [dj-twenty-six/dj-twenty-six.github.io#16]
버전관련건 1.1.0에서 요구사항을 반영해서 수정했을 때 1.1.1로 수정하는지, 
버그 수정에 관련해서만 올리는건지 궁금합니다.

**Comment by pySatellite** [comment]
https://semver.org/lang/ko/ 

버전을 주.부.수 숫자로 하고:

기존 버전과 호환되지 않게 API가 바뀌면 “주(主) 버전”을 올리고,
기존 버전과 호환되면서 새로운 기능을 추가할 때는 “부(部) 버전”을 올리고,
기존 버전과 호환되면서 버그를 수정한 것이라면 “수(修) 버전”을 올린다.
주.부.수 형식에 정식배포 전 버전이나 빌드 메타데이터를 위한 라벨을 덧붙이는 방법도 있다.
