### ISSUE TITLE
PP branch 관련해서 성공은 했는데 의문점생겨서 질문드립니다.

### ISSUE THREAD

**Issue by shims94** [dj-twenty-six/dj-twenty-six.github.io#18]
따로 PP branch생성은 안했고, 칠판 요구사항을 확인했을때
제 branch(재호)를 범수님 branch에 merge하는거여서 
git remote update를하고 git switch 범수님 브랜치로 브랜치를 전환 후 
git merge 재호브랜치로 합쳤습니다.

이후에 합쳐진 부분에 index.html을 vim으로 수정해서 결과적으로 도커환경 테스트까지 성공은 했는데,
올바른 방법인지 궁금합니다.

또한 범수님 브랜치로 합쳐져서 커밋을 했을때 제가아닌 범수님 PR에 업데이트가 되는데,
범수님 브랜치로 합쳤기때문에 PR도 범수님 브랜치에서 작성하는게 맞는지 궁금합니다.

**Comment by pySatellite** [comment]
문제 없어요 ~~
