### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by Sam1000won** [dj-twenty-six/dj-twenty-six.github.io#21]
![스크린샷 2023-10-23 110308](https://github.com/dj-twenty-six/dj-twenty-six.github.io/assets/135206238/1bcec973-219d-4b88-ab1c-9f7509b13158)

firebase into 설정하고
firebase deploy 실행시 이런 오류가 나옵니다.

**Comment by pySatellite** [comment]
firebase init 에서 부터 다시 해봐야겠네요.

아래 pr 을 보면서 같이 해보아요.

- https://github.com/dj-twenty-six/dj-twenty-six.github.io/pull/20

**Comment by pySatellite** [comment]
해당 계정이 긴 히스토리를 갖고 있어서 새로운 구글 계정 생성하여 해결
